import type { Internship } from '../../types/internship.types';

export const mockInternships: Internship[] = [
    {
        _id: '1',
        title: 'Stage Développement Web',
        description: "Développement d'applications web modernes",
        duration: '6 mois',
        startDate: '2026-03-01',
        type: 'Hybride',
        adress: 'Paris',
        company: {
            _id: 'c1',
            name: 'TechCorp',
            email: 'contact@techcorp.fr',
            logoUrl: 'https://ui-avatars.com/api/?name=TechCorp&background=random',
        },
        createdAt: '2026-01-10',
        isCoverLetterRequired: false,
        applications: [],
    },
    {
        _id: '2',
        title: 'Stage Marketing Digital',
        description: 'Stratégie marketing et réseaux sociaux',
        duration: '4 mois',
        startDate: '2026-04-01',
        type: 'Présentiel',
        adress: 'Lyon',
        company: {
            _id: 'c2',
            name: 'Creative Agency',
            email: 'contact@creative.fr',
            logoUrl: 'https://ui-avatars.com/api/?name=Creative+Agency&background=random',
        },
        createdAt: '2026-01-09',
        isCoverLetterRequired: false,
        applications: [],
    },
    {
        _id: '3',
        title: 'Stage Data Science',
        description: 'Analyse de données et machine learning',
        duration: '6 mois',
        startDate: '2026-05-01',
        type: 'Télétravail',
        adress: 'Toulouse',
        company: {
            _id: 'c3',
            name: 'DataLab',
            email: 'contact@datalab.fr',
            logoUrl: 'https://ui-avatars.com/api/?name=DataLab&background=random',
        },
        createdAt: '2026-01-08',
        isCoverLetterRequired: true,
        applications: [],
    },
    {
        _id: '4',
        title: 'Stage Design UX/UI',
        description: "Conception d'interfaces utilisateur",
        duration: '5 mois',
        startDate: '2026-03-15',
        type: 'Hybride',
        adress: 'Bordeaux',
        company: {
            _id: 'c4',
            name: 'Design Studio',
            email: 'contact@designstudio.fr',
            logoUrl: 'https://ui-avatars.com/api/?name=Design+Studio&background=random',
        },
        createdAt: '2026-01-07',
        isCoverLetterRequired: false,
        applications: [],
    },
    {
        _id: '5',
        title: 'Stage Gestion de Projet',
        description: 'Coordination de projets IT',
        duration: '6 mois',
        startDate: '2026-04-01',
        type: 'Présentiel',
        adress: 'Nantes',
        company: {
            _id: 'c5',
            name: 'Consulting Group',
            email: 'contact@consulting.fr',
            logoUrl: 'https://ui-avatars.com/api/?name=Consulting+Group&background=random',
        },
        createdAt: '2026-01-06',
        isCoverLetterRequired: false,
        applications: [],
    },
    {
        _id: '6',
        title: 'Stage Cybersécurité',
        description: "Sécurité des systèmes d'information",
        duration: '6 mois',
        startDate: '2026-06-01',
        type: 'Hybride',
        adress: 'Lille',
        company: {
            _id: 'c6',
            name: 'SecureNet',
            email: 'contact@securenet.fr',
            logoUrl: 'https://ui-avatars.com/api/?name=SecureNet&background=random',
        },
        createdAt: '2026-01-05',
        isCoverLetterRequired: true,
        applications: [],
    },
];
